-- MySQL Script generated by MySQL Workbench
-- Fri Jan  3 22:37:54 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema NimbusKYC
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `NimbusKYC` ;

-- -----------------------------------------------------
-- Schema NimbusKYC
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `NimbusKYC` ;
USE `NimbusKYC` ;

-- -----------------------------------------------------
-- Table `NimbusKYC`.`MasterCatalog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `NimbusKYC`.`MasterCatalog` ;

CREATE TABLE IF NOT EXISTS `NimbusKYC`.`MasterCatalog` (
  `idMasterCatalog` VARCHAR(36) NOT NULL,
  `Element` VARCHAR(50) NOT NULL,
  `Value` VARCHAR(50) NOT NULL,
  `Category` VARCHAR(50) NOT NULL,
  `Status` TINYINT(1) NOT NULL,
  `State` VARCHAR(45) NOT NULL,
  `System` VARCHAR(45) NOT NULL,
  `CreateDate` TIMESTAMP(6) NOT NULL,
  `LatestUpdate` TIMESTAMP(6) NOT NULL,
  `ConsecutiveID` INT NOT NULL,
  PRIMARY KEY (`idMasterCatalog`),
  UNIQUE INDEX `idMasterCatalog_UNIQUE` (`idMasterCatalog` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NimbusKYC`.`Candidate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `NimbusKYC`.`Candidate` ;

CREATE TABLE IF NOT EXISTS `NimbusKYC`.`Candidate` (
  `idCandidate` VARCHAR(36) NOT NULL,
  `FirstName` VARCHAR(50) NOT NULL,
  `MiddleName` VARCHAR(50) NULL,
  `LastName` VARCHAR(50) NOT NULL,
  `Gender` TINYINT(1) NOT NULL,
  `BirthDate` DATE NOT NULL,
  `NationalID` VARCHAR(45) NOT NULL,
  `DigitalSignature` VARCHAR(45) NOT NULL,
  `Status` TINYINT(1) NOT NULL,
  `State` VARCHAR(45) NOT NULL,
  `CreateDate` TIMESTAMP(6) NOT NULL,
  `LatestUpdate` TIMESTAMP(6) NOT NULL,
  `ConsecutiveID` INT NOT NULL,
  PRIMARY KEY (`idCandidate`),
  UNIQUE INDEX `idCandidate_UNIQUE` (`idCandidate` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NimbusKYC`.`Contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `NimbusKYC`.`Contact` ;

CREATE TABLE IF NOT EXISTS `NimbusKYC`.`Contact` (
  `idContact` VARCHAR(36) NOT NULL,
  `Candidate_idCandidate` VARCHAR(50) NOT NULL,
  `Phone` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Status` TINYINT(1) NOT NULL,
  `State` VARCHAR(45) NOT NULL,
  `CreateDate` TIMESTAMP(6) NOT NULL,
  `LatestUpdate` TIMESTAMP(6) NOT NULL,
  `ConsecutiveID` INT NOT NULL,
  PRIMARY KEY (`idContact`),
  INDEX `fk_Contact_Candidate_idx` (`Candidate_idCandidate` ASC) VISIBLE,
  CONSTRAINT `fk_Contact_Candidate`
    FOREIGN KEY (`Candidate_idCandidate`)
    REFERENCES `NimbusKYC`.`Candidate` (`idCandidate`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NimbusKYC`.`Address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `NimbusKYC`.`Address` ;

CREATE TABLE IF NOT EXISTS `NimbusKYC`.`Address` (
  `idAddress` VARCHAR(36) NOT NULL,
  `Candidate_idCandidate` VARCHAR(50) NOT NULL,
  `Country` VARCHAR(45) NOT NULL,
  `StateProvince` VARCHAR(45) NOT NULL,
  `Municipality` VARCHAR(45) NULL,
  `Neighborhood` VARCHAR(45) NULL,
  `ExternalNumber` VARCHAR(45) NULL,
  `InternalNumber` VARCHAR(45) NULL,
  `LocationReference` VARCHAR(45) NULL,
  `Zipcode` VARCHAR(5) NOT NULL,
  `CreateDate` TIMESTAMP(6) NOT NULL,
  `LatestUpdate` TIMESTAMP(6) NOT NULL,
  `Status` TINYINT(1) NOT NULL,
  `State` VARCHAR(45) NOT NULL,
  `ConsecutiveID` INT NOT NULL,
  PRIMARY KEY (`idAddress`),
  INDEX `fk_Address_Candidate1_idx` (`Candidate_idCandidate` ASC) VISIBLE,
  CONSTRAINT `fk_Address_Candidate1`
    FOREIGN KEY (`Candidate_idCandidate`)
    REFERENCES `NimbusKYC`.`Candidate` (`idCandidate`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NimbusKYC`.`Document`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `NimbusKYC`.`Document` ;

CREATE TABLE IF NOT EXISTS `NimbusKYC`.`Document` (
  `idDocument` VARCHAR(36) NOT NULL,
  `Candidate_idCandidate` VARCHAR(36) NOT NULL,
  `DocumentFile` VARCHAR(45) NOT NULL,
  `Type` VARCHAR(45) NOT NULL,
  `Location` VARCHAR(500) NOT NULL,
  `Metadata` VARCHAR(500) NOT NULL,
  `ExpiracyDate` DATE NULL,
  `Status` TINYINT(1) NOT NULL,
  `State` VARCHAR(45) NOT NULL,
  `CreateDate` TIMESTAMP(6) NOT NULL,
  `LatestUpdate` TIMESTAMP(6) NOT NULL,
  `ConsecutiveID` INT NOT NULL,
  PRIMARY KEY (`idDocument`),
  INDEX `fk_Document_Candidate1_idx` (`Candidate_idCandidate` ASC) VISIBLE,
  CONSTRAINT `fk_Document_Candidate1`
    FOREIGN KEY (`Candidate_idCandidate`)
    REFERENCES `NimbusKYC`.`Candidate` (`idCandidate`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NimbusKYC`.`Device`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `NimbusKYC`.`Device` ;

CREATE TABLE IF NOT EXISTS `NimbusKYC`.`Device` (
  `idDevice` VARCHAR(36) NOT NULL,
  `Candidate_idCandidate` VARCHAR(36) NOT NULL,
  `Brand` VARCHAR(45) NOT NULL,
  `Model` VARCHAR(45) NOT NULL,
  `CreateDate` TIMESTAMP(6) NOT NULL,
  `LatestUpdate` TIMESTAMP(6) NOT NULL,
  `Status` TINYINT(1) NOT NULL,
  `State` VARCHAR(45) NOT NULL,
  `ConsecutiveID` INT NOT NULL,
  PRIMARY KEY (`idDevice`),
  INDEX `fk_Device_Candidate1_idx` (`Candidate_idCandidate` ASC) VISIBLE,
  CONSTRAINT `fk_Device_Candidate1`
    FOREIGN KEY (`Candidate_idCandidate`)
    REFERENCES `NimbusKYC`.`Candidate` (`idCandidate`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NimbusKYC`.`Biometrics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `NimbusKYC`.`Biometrics` ;

CREATE TABLE IF NOT EXISTS `NimbusKYC`.`Biometrics` (
  `idBiometrics` VARCHAR(26) NOT NULL,
  `Candidate_idCandidate` VARCHAR(36) NOT NULL,
  `Type` VARCHAR(45) NOT NULL,
  `Location` VARCHAR(500) NOT NULL,
  `Status` TINYINT(1) NOT NULL,
  `State` VARCHAR(45) NOT NULL,
  `CreateDate` TIMESTAMP(6) NOT NULL,
  `LatestUpdate` TIMESTAMP(6) NOT NULL,
  `ConsecutiveID` INT NOT NULL,
  PRIMARY KEY (`idBiometrics`),
  INDEX `fk_Biometrics_Candidate1_idx` (`Candidate_idCandidate` ASC) VISIBLE,
  CONSTRAINT `fk_Biometrics_Candidate1`
    FOREIGN KEY (`Candidate_idCandidate`)
    REFERENCES `NimbusKYC`.`Candidate` (`idCandidate`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NimbusKYC`.`Location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `NimbusKYC`.`Location` ;

CREATE TABLE IF NOT EXISTS `NimbusKYC`.`Location` (
  `idLocation` INT NOT NULL,
  `Candidate_idCandidate` VARCHAR(36) NOT NULL,
  `Coordinates` POINT NOT NULL,
  `CreateDate` TIMESTAMP(6) NOT NULL,
  `LatestUpdate` TIMESTAMP(6) NOT NULL,
  `Status` TINYINT(1) NOT NULL,
  `State` VARCHAR(45) NOT NULL,
  `ConsecutiveID` INT NOT NULL,
  PRIMARY KEY (`idLocation`),
  INDEX `fk_Location_Candidate1_idx` (`Candidate_idCandidate` ASC) VISIBLE,
  UNIQUE INDEX `idLocation_UNIQUE` (`idLocation` ASC) VISIBLE,
  CONSTRAINT `fk_Location_Candidate1`
    FOREIGN KEY (`Candidate_idCandidate`)
    REFERENCES `NimbusKYC`.`Candidate` (`idCandidate`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

DELIMITER $$

CREATE TRIGGER set_consecutive_id_mastercatalog
BEFORE INSERT ON `NimbusKYC`.`MasterCatalog`
FOR EACH ROW
BEGIN
    -- Set the ConsecutiveID of the new row to the current maximum + 1
    SET NEW.ConsecutiveID = COALESCE((SELECT MAX(ConsecutiveID) FROM `NimbusKYC`.`MasterCatalog`), 0) + 1;
END;

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
